options:
  merge-default-rules: false
  max-warnings: 10
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations: 2
  placeholder-in-extend: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-attribute-selectors: 0
  one-declaration-per-line: 2
  property-sort-order: 0
  no-color-keywords: 2
  no-combinators: 0
  no-extends: 0
  no-css-comments: 0
  no-debug: 0
  no-warn: 0
  no-disallowed-properties: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 2
  no-empty-rulesets: 1
  no-trailing-whitespace: 0
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 2
  no-url-protocols: 0
  url-quotes: 2
  no-ids: 2
  no-important: 2
  pseudo-element: 2
  single-line-per-selector: 2
  bem-depth:
    - 2
    -
      max-depth: 1
  nesting-depth:
    - 3
    -
      max-depth: 2
  no-duplicate-properties:
    - 1
    -
      exclude: [border, margin, padding]
  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  variable-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  function-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  border-zero:
    - 1
    -
      convention: '0'
  clean-import-paths:
    - 0
    -
      leading-underscore: true
      filename-extension: false
  empty-args:
    - 1
    -
      include: true
  zero-unit:
    - 2
    -
      include: false
  shorthand-values:
  - 1
  -
    allowed-shorthands:
      - 1
      - 2
  no-invalid-hex: 2
  hex-notation:
    - 1
    -
      style: lowercase
  hex-length:
    - 0
    -
      style: long
  no-color-literals:
    - 2
    -
      allow-map-identifiers: true
      allow-rgba: false
      allow-variable-identifiers: true
  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true
  property-units:
    - 0
    -
      global: ['em', 'rem', 'px']
      per-property: {width: ['em', 'rem', 'vw'], height: ['em', 'rem', 'vh']}
  variable-for-property:
    - 2
    -
      properties:
        - color
        - font-family